### ISSUE TITLE
My profile shows a mix of the old talk description and the new one.

### ISSUE THREAD

**Issue by Shelmith-Kariuki** [rstudio/rstudio-global-2021-program#63]
Please edit my talk description to reflect the new description.

This is the old one: 
![image](https://user-images.githubusercontent.com/37449624/104913640-f7153880-599e-11eb-9067-035aefdb030b.png)

This is the latest and most accurate one
![image](https://user-images.githubusercontent.com/37449624/104913691-0ac09f00-599f-11eb-8416-b29528790105.png)

https://global.rstudio.com/student/activity/40639

**Comment by gregswinehart** [comment]
fixed on Intellum / global.rstudio.com!
